#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Apply per-slug content specs (H2 fixes, new sections, FAQ rewrite, excerpts,
surgical text repairs). Verifies hard guardrails before writing."""
import sys, os, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _gb001r_lib as L
from _gb001r_s2t import s2tw, spec_s2tw

VERBOSE = "-v" in sys.argv


def apply(slug, spec_cn, do_tw=True):
    """spec_cn keys: 'en', 'zh-cn'. zh-tw generated by conversion."""
    specs = dict(spec_cn)
    if do_tw and "zh-cn" in specs:
        tw = spec_s2tw(specs["zh-cn"])
        if "zh-tw_h2fix" in specs["zh-cn"]:
            tw.setdefault("h2fix", {}).update(specs["zh-cn"]["zh-tw_h2fix"])
        specs["zh-tw"] = tw
    results = {}
    for sub, lang, floor in L.LANGS:
        spec = specs.get(lang)
        if not spec: continue
        before = L.read(sub, slug)
        h = before
        notes = []

        # 1. surgical text repairs (corruption / mistranslation) - BODY only
        reps = spec.get("replace", [])
        if reps:
            he = h.lower().find("</head>")
            fe = h.lower().find("<footer")
            if fe < 0: fe = len(h)
            head, body, tail = h[:he], h[he:fe], h[fe:]
            for old, new in reps:
                if old in body:
                    body = body.replace(old, new); notes.append("repaired")
                elif VERBOSE:
                    notes.append(f"MISS-REPLACE:{old[:24]}")
            h = head + body + tail

        # 2. H2 question conversion / grammar fixes
        for hid, newtext in spec.get("h2fix", {}).items():
            h, ok = L.set_h2_text(h, hid, newtext)
            notes.append("h2ok" if ok else f"H2MISS:{hid}")

        # 3. new sections
        for sec in spec.get("sections", []):
            hid, title, body = sec[0], sec[1], sec[2]
            anchor = sec[3] if len(sec) > 3 else None
            if re.search(r'<h2 id="' + re.escape(hid) + r'"', h):
                notes.append(f"sec-skip:{hid}"); continue
            if anchor:
                nh = L.insert_before_h2(h, anchor, f'<h2 id="{hid}">{title}</h2>\n{body.strip()}')
                if nh: h = L.add_toc(nh, hid, title); notes.append(f"sec:{hid}")
                else: notes.append(f"SECMISS:{hid}")
            else:
                nh = L.insert_section(h, hid, title, body)
                if nh: h = nh; notes.append(f"sec:{hid}")
                else: notes.append(f"SECMISS:{hid}")

        # 4. FAQ rewrite
        if spec.get("faq"):
            nh = L.replace_faq(h, spec["faq"], lang)
            if nh: h = nh; notes.append(f"faq:{len(spec['faq'])}")
            else: notes.append("FAQMISS")

        # 5. regenerate body JSON-LD from the on-page FAQ
        h, ldst = L.sync_jsonld(h, lang)
        notes.append(f"ld:{ldst}")

        # 6. excerpts
        if spec.get("excerpts"):
            h = L.fill_excerpts(h, spec["excerpts"])
            notes.append("excerpt")

        errs = L.guard(before, h, sub, slug)
        if errs:
            results[lang] = ("FAIL " + ";".join(errs), None, None); continue
        if h != before:
            L.write(sub, slug, h)
        m0 = L.metric(before, lang); m1 = L.metric(h, lang)
        results[lang] = (" ".join(notes), m0, m1)
    return results


def report(slug, spec_cn, do_tw=True):
    res = apply(slug, spec_cn, do_tw)
    for lang in ("en", "zh-cn", "zh-tw"):
        if lang not in res: continue
        st, m0, m1 = res[lang]
        print(f"{slug[:44]:44} {lang:6} {str(m0):>5} -> {str(m1):>5} | {st[:100]}")
