#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gbatch_003 slug 13 — ai-driven-data-strategy-enterprise-competitive-advantage"""
import sys
sys.path.insert(0, '/Users/kennethkwok/Beehive Strategy/0 - New Beehive/website/_batch_pipeline')
from _gb003_lib import process, stats
from _gb001_s2t import s2tw

SLUG = 'ai-driven-data-strategy-enterprise-competitive-advantage'

EN_RENAMES = {
    'The Strategic Context for Enterprise AI':
        'Why Does Data Strategy Decide AI Competitive Advantage?',
    'Framework for Strategic Decision-Making':
        'Which Framework Should Guide AI Data Strategy Decisions?',
    'Organizational Change and Capability Building':
        'How Do You Build the Capability an AI Data Strategy Needs?',
    'Measuring Strategic Impact':
        'How Should You Measure the Impact of an AI Data Strategy?',
}

EN_INSERTS = [
    ('Which Data Assets Actually Create Competitive Advantage?',
     'which-data-assets-actually-create-competitive-advantage',
     '<p>Most data strategies fail because they treat all data as equally valuable. Only a subset is defensible, and identifying it is the first strategic act rather than an analytical one. Three tests separate advantage-creating data from the rest.</p>'
     '<ul>'
     '<li><strong>Exclusivity.</strong> Do you have it and competitors cannot buy it? Transaction history, service interactions, sensor telemetry, and proprietary process data are exclusive. Market data, demographic overlays, and public benchmarks are not — everyone can license them, so they cannot differentiate anything.</li>'
     '<li><strong>Decision proximity.</strong> Does the data sit close to a decision that moves money? A dataset that informs a weekly pricing decision is more valuable than a larger dataset that informs an annual planning cycle, because value compounds with decision frequency.</li>'
     '<li><strong>Compounding.</strong> Does using it make it better? Data that improves with use — feedback loops, labels generated by customers, correction data from users — creates a moat that widens over time. Static reference data does not.</li>'
     '</ul>'
     '<p>Applying these three tests usually shrinks the priority list dramatically, which is the point. Enterprises rarely lack data; they lack agreement on which data matters. Naming the ten or twenty assets that pass all three tests, governing those first, and explicitly de-prioritising the rest converts a data strategy from an inventory project into a competitive one.</p>'),

    ('How Should an Enterprise Sequence Its AI Data Investments?',
     'how-should-an-enterprise-sequence-its-ai-data-investments',
     '<p>Sequencing is where strategy becomes a calendar, and the most common error is sequencing by technical dependency rather than by decision value. Three phases work, each with an explicit exit gate.</p>'
     '<ol>'
     '<li><strong>Foundation (0–6 months).</strong> Govern the assets that passed the three tests: inventory, ownership, quality monitoring, and a semantic layer that defines the metrics every AI system will consume. The gate is not "the catalogue is complete" but "a new use case can be onboarded in days because the definitions and controls already exist."</li>'
     '<li><strong>Proof at scale (6–18 months).</strong> Deploy AI on two to four decisions where the data is ready and the value is measurable, each with a control group. The gate is evidence: quantified EBIT or cost impact on at least one decision, attributable against the holdout.</li>'
     '<li><strong>Industrialisation (18 months onward).</strong> Extend the governed layer across domains, federate ownership to the teams closest to the data, and make the access layer the default path for every new AI use case. The gate is that the marginal cost of the next deployment falls measurably, because controls are inherited rather than rebuilt.</li>'
     '</ol>'
     '<p>Two rules keep the sequence honest. Never start a use case whose data is not in the governed layer — that is how pilots become orphaned. And never fund the second phase on the promise of the first; require the measured result, because the discipline of producing it is what makes the rest of the portfolio credible.</p>'),

    ('What Does an AI Data Operating Model Look Like?',
     'what-does-an-ai-data-operating-model-look-like',
     '<p>Strategy survives on operating model, not on documents. Four roles and three rituals cover most of what separates organisations that execute from those that publish strategies.</p>'
     '<ul>'
     '<li><strong>Executive owner.</strong> Accountable for a business outcome, not for a platform. Without this, every prioritisation argument resolves to whoever speaks loudest.</li>'
     '<li><strong>Domain data owners.</strong> Accountable for the quality, definitions, and access rules of their data, federated rather than centralised, because the people closest to the data are the only ones who can classify it correctly.</li>'
     '<li><strong>Platform team.</strong> Implements the controls — access, lineage, monitoring, audit — once, at the layer where data is reached, so domains do not each invent them.</li>'
     '<li><strong>Centre of excellence.</strong> Sets standards, arbitrates disputes, and holds the reusable assets: the semantic layer, the evaluation harness, the incident playbook.</li>'
     '</ul>'
     '<p>The three rituals are a quarterly portfolio review that funds or kills use cases on measured results; a monthly data quality review with named owners and open remediation items; and a standing architecture review that asks, for every new AI use case, whether it can reach data through the governed path. The last one is the control that prevents shadow AI — not prohibition, but making the compliant route the fastest one available.</p>'),

    ('How Do You Keep an AI Data Strategy From Becoming a Slide Deck?',
     'how-do-you-keep-an-ai-data-strategy-from-becoming-a-slide-deck',
     '<p>The failure mode of a data strategy is not being wrong; it is being inert. Three mechanisms convert a strategy document into something the organisation actually operates against.</p>'
     '<p>First, tie funding to the strategy explicitly. Every AI use case request should have to name the governed data assets it depends on and the decision it changes; requests that cannot answer both go back rather than into the backlog. This single rule does more to govern the portfolio than any committee, because it makes the strategy the path of least resistance instead of an additional hurdle.</p>'
     '<p>Second, publish the scorecard. The metrics a strategy is judged by — use case onboarding time, governed data coverage, measured EBIT impact, marginal deployment cost — should be visible to the same audience that approved the strategy. Visibility changes behaviour in a way that quarterly reporting does not, because a visible trend line creates accountability between reviews.</p>'
     '<p>Third, review the strategy itself twice a year against reality. Model capabilities, regulation, and the competitive set all move faster than annual planning cycles. A strategy that is never revised quietly stops describing the business it is supposed to guide, and the organisations that treat it as a living document are the ones that keep compounding while others re-litigate the same decisions every year.</p>'),
]

EN_FAQ = [
    ('What is an AI-driven data strategy?',
     'It is the deliberate alignment of data assets, AI capabilities, and business priorities to create durable competitive advantage. Concretely, it means deciding which data to govern first, which decisions to fund with AI, and how to organise for execution — rather than accumulating use cases. McKinsey research finds that fewer than one in ten organisations report significant bottom-line impact from AI, while leaders that embed AI across value chains achieve EBITDA uplifts of 20 to 25 percent. The difference between those outcomes is not model quality; it is strategy.'),
    ('Why has data strategy become an AI strategy?',
     'Because models are only as differentiated as the data they run on. Frontier models are available to every competitor, so the durable advantage sits in exclusive data, in the definitions that make it usable, and in the operating discipline that keeps it current. There is no credible AI strategy that is not also a data strategy: an organisation that licenses the same model as its competitor and feeds it the same public data will get the same answers. Advantage comes from the data nobody else has, governed well enough to be used by AI systems safely.'),
    ('Which data assets should be governed first?',
     'The ones that pass three tests simultaneously: exclusivity, because competitors cannot buy them; decision proximity, because they inform frequent, money-moving decisions rather than annual planning; and compounding, because using them improves them. Applying these tests usually reduces the priority list to a handful of assets, which is the point — most enterprises already own the data required for advantage and simply have not organised, governed, and activated it. That is a strategy failure, not a resource failure.'),
    ('How should the return on an AI data strategy be measured?',
     'Measure in three tiers, baselined before the programme starts. Operational: onboarding time for a new use case, share of data assets with named owners, quality incident count and resolution time. Business: EBIT or cost impact on the decisions AI touched, measured against a control group rather than against last quarter. Strategic: the marginal cost and time of each successive deployment, which should fall as controls are inherited. The third tier is the real test of strategy, because it shows whether the enterprise is building a capability or accumulating projects.'),
    ('How long does it take to build an AI-driven data strategy?',
     'The strategy itself should take six to eight weeks: two weeks to identify advantage-creating assets, two to three weeks to agree the operating model and portfolio, and two to three weeks to baseline and sequence. Execution is longer — a foundation phase of about six months, proof at scale over six to eighteen months, and industrialisation from eighteen months onward. Organisations that try to compress the strategy phase usually spend the difference later, on use cases built on data that was never governed.'),
]

ZH_RENAMES = {
    '当前格局与关键趋势': '为什么数据战略决定AI竞争优势？',
    '实施框架与最佳实践': '应该用什么样的框架指导数据战略决策？',
    '衡量影响与展示价值': '如何衡量数据战略的业务影响？',
    '克服常见挑战': '落地数据战略最常见的挑战是什么？',
    '规模化推广的关键成功因素': '规模化推广的关键成功因素是什么？',
    '从试点到规模化生产的路径': '从试点走向规模化生产的路径是什么？',
    '技术基础设施与实施考量': '技术基础设施与实施上有哪些考量？',
}

TW_RENAMES = {
    'Framework for Strategic Decision-Making': '該用什麼樣的框架指導數據戰略決策？',
    'Organizational Change and Capability Building': '如何建立數據戰略所需的能力？',
    'Measuring Strategic Impact': '該如何衡量數據戰略的影響？',
    '常見問題': '常見問題',
    '規模化推廣的關鍵成功因素': '規模化推廣的關鍵成功因素是什麼？',
    '技術基礎設施與實施考量': '技術基礎設施與實施上有哪些考量？',
    '中國市場特有的實施優勢': '華語市場在數據戰略落地上的優勢是什麼？',
}

ZH_FAQ = [
    ('什么是AI驱动的数据战略？',
     '它是把数据资产、AI能力与业务优先级有意识地对齐，以构建可持续的竞争优势。具体来说，它意味着先决定治理哪些数据、用AI投入哪些决策、以及如何组织执行，而不是不断堆砌用例。麦肯锡的研究发现，只有不到十分之一的组织报告AI带来了显著的利润影响，而将AI嵌入价值链各环节的领导者则实现了20%到25%的EBITDA提升。造成这种差距的不是模型质量，而是战略。'),
    ('为什么数据战略已经变成AI战略？',
     '因为模型的差异化上限，取决于它所运行的数据。前沿模型对所有竞争者都可得，因此持久的优势存在于独占数据、让数据可用的定义，以及保持数据时效性的运营纪律之中。不存在"不是数据战略"的可信AI战略：如果一家企业与竞争对手使用同一个授权模型、喂入同样的公开数据，它得到的答案也必然相同。优势来自别人没有的数据，而且这些数据必须被治理到足以让AI系统安全地使用。'),
    ('应该优先治理哪些数据资产？',
     '优先治理同时通过三项检验的资产：独占性（竞争对手买不到）、决策贴近度（支撑高频且影响损益的决策，而不是年度规划）、以及复利性（越用越好）。套用这三项检验通常会把优先级清单缩短到少数几项资产，而这正是重点——多数企业其实已经拥有形成优势所需的数据，只是没有组织、治理并激活它们。这是战略失败，而不是资源不足。'),
    ('AI数据战略的回报应该如何衡量？',
     '建议分三层衡量，并在项目启动前建立基线。运营层：新用例的接入时间、有具名责任人的数据资产占比、质量事故数量与解决时长。业务层：AI所触及决策的利润或成本影响，并且要与对照组比较，而不是与上季度比较。战略层：每一次后续部署的边际成本与时间，它应当随着控制的继承而下降。第三层才是真正的战略检验，因为它显示企业是在构建一项能力，还是在累积一堆项目。'),
    ('制定AI驱动的数据战略需要多长时间？',
     '战略本身应该在六到八周内完成：两周识别能创造优势的资产，两到三周就运营模式与投资组合达成共识，两到三周完成基线与排序。执行周期更长——基础阶段约六个月，六到十八个月完成规模化验证，十八个月之后进入工业化阶段。试图压缩战略阶段的组织，通常会在之后以"用例建在从未被治理的数据上"的形式把时间还回去。'),
]


def run():
    b = {lg: stats(SLUG, lg) for lg in ('en', 'zh-cn', 'zh-tw')}
    process(SLUG, 'en', h2_renames=EN_RENAMES, inserts=EN_INSERTS, faq=EN_FAQ, drop_body_faq=True)
    process(SLUG, 'zh-cn', h2_renames=ZH_RENAMES, faq=ZH_FAQ)
    process(SLUG, 'zh-tw', h2_renames=TW_RENAMES, faq=[(s2tw(q), s2tw(a)) for q, a in ZH_FAQ],
            drop_body_faq=True)
    for lg in ('en', 'zh-cn', 'zh-tw'):
        print(lg, b[lg], '->', stats(SLUG, lg))


if __name__ == '__main__':
    run()
