#!/usr/bin/env python3
"""EN body expansion, batch 1 (4 slugs)."""
import sys
sys.path.insert(0, '/Users/kennethkwok/Beehive Strategy/0 - New Beehive/website/_batch_pipeline')
from _gb002_lib import apply_ops

DATA = {}

DATA['ai-budget-justification-framework-q4-planning'] = dict(before='__FAQ__', inserts=[
    ("How Should You Build the ROI Model Line by Line?", """
<p>An AI business case survives the Q4 review when every number in it traces back to a source the approver already trusts. Build it in five lines, and resist the urge to add a sixth.</p>
<p><strong>Line 1 &mdash; baseline cost.</strong> What does the process cost today in fully loaded labour hours plus vendor spend? Take it from the finance system, not from a team estimate. If a reporting cycle consumes 6,000 hours a year across twelve people at a blended loaded rate of $95, the baseline is $570,000 &mdash; defensible because it reconciles to payroll.</p>
<p><strong>Line 2 &mdash; expected reduction.</strong> State the percentage improvement and the mechanism that produces it. "Forty per cent of analyst hours are redeployed to higher-value work" can be instrumented; "productivity improves" cannot. Anchor the percentage to a pilot measurement or to a comparable deployment, and say which one.</p>
<p><strong>Line 3 &mdash; cost to achieve.</strong> Licences, integration effort, internal project time, change management, and the steady-state run cost of the platform. Understating this line is the fastest way to lose credibility next year, when actuals arrive and the variance has to be explained.</p>
<p><strong>Line 4 &mdash; timing.</strong> Benefits do not land on day one. Model a ramp: nothing in the first quarter after go-live, half the benefit in the second, full run-rate from the third. Approvers discount optimistic timing far more heavily than they discount optimistic magnitude, because timing is where past projects have disappointed them.</p>
<p><strong>Line 5 &mdash; payback and sensitivity.</strong> Show the month at which cumulative benefit exceeds cumulative cost, then show the pessimistic case: half the benefit, twice the integration effort. A case that still pays back inside eighteen months under those assumptions is very hard to reject.</p>
<p>Two things belong outside the model. Do not count avoided headcount you have no plan to remove &mdash; approvers know that saving only materialises through attrition or redeployment, and they will ask which. And do not stack use cases to make a marginal individual case look acceptable: five thin cases presented as one portfolio reads as hedging.</p>
"""),
    ("What Risk Register Do Approvers Expect to See?", """
<p>A risk register is not a list of things that might go wrong. It is evidence that you have already priced the downside and decided who owns it. Approvers read it to judge operating maturity, and a register containing only technical risks signals a team that has never run a production system.</p>
<p>Structure it around five categories. <strong>Delivery risk</strong> covers data readiness, integration complexity, and dependency on a vendor's roadmap. <strong>Adoption risk</strong> covers whether the people whose work changes will actually use the system; name the specific teams and the specific behaviour change required. <strong>Model risk</strong> covers accuracy thresholds, drift, and what happens when the model is wrong &mdash; including who reviews the output before it reaches a customer or a regulator. <strong>Compliance risk</strong> covers the regimes that apply to the use case and the evidence you will need to produce. <strong>Run risk</strong> covers the ongoing cost and the internal capability required to operate the thing after the project team disbands.</p>
<p>Score each risk twice: once for likelihood, once for impact, on a three-point scale rather than a five-point one. Three points forces a decision; five points invites everyone to pick three. Then attach a mitigation and an owner to every item scoring above your threshold. An unowned risk is a risk the approver assumes they will end up owning, which is exactly the reaction you are trying to avoid.</p>
<p>The register should also state what you will do if the pilot fails. A defined stop condition &mdash; accuracy below a threshold at week eight, or adoption below a level at month three &mdash; is the single strongest credibility signal in the pack. It tells the committee that the money buys a decision, not an obligation.</p>
"""),
])

DATA['ai-center-of-excellence-design'] = dict(before='What Should Leaders Conclude from This Analysis?', inserts=[
    ("How Should a CoE Be Staffed and Funded?", """
<p>Staffing is where most CoE charters quietly fail. The charter says the CoE will "enable the business", the budget funds four people, and eighteen months later the CoE is a helpdesk. Size the team against the owned capabilities, not against ambition.</p>
<p>A workable minimum for an enterprise CoE is five roles. A <strong>lead</strong> who owns the mandate and reports to a sponsor with budget authority. A <strong>platform engineer or two</strong> who own the shared tooling, the evaluation harness, and the deployment path. A <strong>governance lead</strong> who owns the risk taxonomy, the model inventory, and the review cadence &mdash; this is a different person from the platform engineer and should not be a part-time assignment. A <strong>data or semantic-layer owner</strong> who makes sure the definitions the models depend on are consistent. And a <strong>enablement or embedded role</strong> whose job is to sit with business units long enough to make the first two or three use cases real.</p>
<p>Everything else can be borrowed. Legal, security, procurement, and change management should be named contributors with allocated time, not headcount inside the CoE. Borrowing keeps the centre small and keeps the functions accountable for their own standards.</p>
<p>Funding model matters as much as headcount. Three patterns dominate. <strong>Central funding</strong> is simplest and works for the first twelve to eighteen months, when the CoE is building shared assets the business cannot yet value &mdash; but it creates no demand discipline. <strong>Recharge or consumption funding</strong>, where business units pay for platform usage, creates real demand signal but pushes teams toward shadow tooling if internal pricing is not competitive with public cloud alternatives. <strong>Hybrid funding</strong> is the practical answer: the centre's fixed costs &mdash; platform, governance, enablement &mdash; are centrally funded as shared infrastructure, while use-case build costs sit in the business unit's budget.</p>
<p>Set the review point at twelve months regardless of model. By then the CoE should be able to show production deployments, a completed governance cycle, and at least one use case that a business unit would fund again from its own budget. If it cannot, the mandate &mdash; not the headcount &mdash; is the thing to revisit.</p>
"""),
])

DATA['ai-center-of-excellence-operating-model'] = dict(before='What Are the Key Takeaways?', inserts=[
    ("How Do Centralized, Federated and Hub-and-Spoke Models Differ in Practice?", """
<p>The three structural patterns are easy to draw and harder to choose between, because the differences only show up under load. What follows is what each one actually feels like to operate.</p>
<p><strong>Centralized.</strong> One team builds and runs everything. It is fast at the start, produces consistent architecture, and is the right answer when the data foundation is weak or the regulatory burden is high &mdash; you want one place where controls are enforced. The failure mode is throughput: demand grows faster than the centre can hire, business units start queueing, and the queue pushes them to build around the CoE rather than with it. Centralized models work best up to roughly fifteen to twenty concurrent use cases; beyond that they bottleneck unless the centre deliberately shifts to enablement.</p>
<p><strong>Federated.</strong> Capability sits in the business units; the CoE sets standards and convenes. It scales well and keeps domain knowledge close to the problem, which is where the value usually is. The failure mode is drift: without enforced standards, each unit builds its own evaluation approach, its own prompts and retrieval patterns, and its own vendor relationships. Two years in, nobody can answer "what AI are we running?" and the cost of consolidating is higher than the cost of having centralised earlier.</p>
<p><strong>Hub-and-spoke.</strong> The CoE owns the platform, the semantic layer, governance, and the evaluation harness; embedded engineers or product owners in each business unit own the use cases. This is the pattern most enterprises converge on, and it is the right default when you have more than a handful of use cases and more than one business unit with real demand. It is also the hardest to run, because it requires the centre to be genuinely good at two jobs that pull in different directions: enforcing standards and being useful to the people it enforces them on.</p>
<p>The way through that tension is to make the shared layer so much easier than the alternative that compliance is the path of least resistance. If the CoE's deployment path is faster than a team's own, and the semantic layer saves them weeks of data wrangling, spokes will use it because it helps them &mdash; not because a policy says so.</p>
"""),
    ("What Governance Cadence Keeps a CoE From Becoming a Bottleneck?", """
<p>Governance becomes a bottleneck when every decision goes through the same meeting. It stays proportionate when the cadence matches the risk of the decision being made.</p>
<p><strong>Continuous and automated.</strong> Anything checkable by a system should never reach a human queue: data classification, PII detection in prompts, licence checks on models, evaluation thresholds, and cost per request. Automating these removes the bulk of review volume and, more importantly, gives consistent answers.</p>
<p><strong>Weekly and lightweight.</strong> A standing thirty-minute triage for new use-case requests, with a single question: is this low, medium, or high risk? Low-risk work &mdash; internal productivity, no customer data, no regulated decision &mdash; proceeds with registration only. That single rule typically clears more than half of submissions on the day they arrive.</p>
<p><strong>Monthly.</strong> A review of everything in production against the metrics that matter: accuracy against threshold, drift, cost per unit of value, adoption, and incident count. This is a portfolio review, not an approval gate, and the output is a ranked list of interventions.</p>
<p><strong>Quarterly.</strong> A deeper review covering higher-risk deployments, model changes, vendor changes, and the regulatory horizon. This is where the sponsor should be present, because this is where the CoE either renews its mandate or gets a hard question about value.</p>
<p>Publish the service levels for each tier &mdash; how long a medium-risk review takes, what a team must supply, and what happens if the CoE misses its own deadline. A governance function that misses its own commitments loses the moral authority to hold anyone else to theirs.</p>
"""),
])

DATA['ai-competitive-moat-2026'] = dict(before='What Are the Key Takeaways?', inserts=[
    ("Which Feedback Loops Actually Compound?", """
<p>Not every feedback loop is a moat. Most are just logging. A loop compounds only when each cycle makes the next cycle's output better for the next user, and when the resulting asset cannot be bought.</p>
<p>Three loops meet that test in practice. <strong>The correction loop</strong>: users accept, edit, or reject AI output, and those corrections are captured as structured signal rather than discarded. A support organisation that captures which generated answers agents edited, and feeds the edit back into retrieval and prompt selection, improves its deflection rate every month while a competitor starting from the same base model does not. The asset is not the model &mdash; it is the accumulated record of what "right" looks like in your domain.</p>
<p><strong>The outcome loop</strong>: the business result of an AI-assisted decision flows back into the system that made it. Underwriting, pricing, inventory allocation, and maintenance scheduling all generate this naturally. The lender that sees which AI-assisted approvals actually performed, and retrains on realised outcomes rather than proxy labels, pulls steadily ahead of one that only measures model accuracy offline.</p>
<p><strong>The workflow-embedding loop</strong>: the more decisions the system touches, the more context it accumulates, and the harder it becomes to remove. This is the least glamorous and the most durable of the three. Once an operations team runs its daily planning through one interface, switching costs are organisational rather than technical &mdash; and organisational switching costs are what incumbents underestimate and challengers overestimate.</p>
<p>The test for whether a loop is real: pick a period twelve months ago and show that the same input now produces a measurably better output. If you cannot demonstrate that, you have instrumentation, not a moat.</p>
"""),
    ("How Do You Measure Whether Your AI Moat Is Widening?", """
<p>"We have proprietary data" is not a measurement. Four indicators tell you whether the advantage is compounding or eroding, and all four can be tracked from systems you already operate.</p>
<p><strong>Data asset growth, adjusted for usability.</strong> Raw volume is a vanity metric. Measure the volume of data that is governed, labelled where labels matter, and actually reachable by a production system. If governed data is growing slower than raw data, the moat is filling with silt.</p>
<p><strong>Outcome gap versus a generic baseline.</strong> Run a periodic benchmark: your production system against an off-the-shelf model with no proprietary context, on the same live tasks. The gap is your moat, expressed in the unit the business cares about &mdash; accuracy, deflection rate, approval rate at constant loss, or cycle time. Track it quarterly. A widening gap means the system is compounding; a narrowing one means a competitor with a better base model is catching up and your data is not doing enough work.</p>
<p><strong>Switching cost.</strong> How many workflows, integrations, and downstream decisions depend on the system? Count them, and count how many would break if the system were replaced next quarter. This is the defensive half of the moat and the part that shows up in renewal conversations.</p>
<p><strong>Unit economics trend.</strong> Cost per decision served should fall over time even as volume grows, because the shared data and semantic layer amortises. If unit cost is flat while volume grows, you are renting capability rather than building an asset &mdash; and whatever advantage you have is available to anyone with the same budget.</p>
<p>Taken together, these four move the moat conversation from a strategy discussion to a quarterly dashboard. That is the point: moats that are not measured tend to be moats that were never built.</p>
"""),
])

if __name__ == '__main__':
    for slug, d in DATA.items():
        changed = apply_ops(slug, 'en', inserts=d['inserts'], before=d['before'])
        print(('inserted ' if changed else 'noop     ') + slug)
